services:
  - type: web
    name: nakama
    runtime: docker
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nakama-db
          property: connectionString
      - key: NAKAMA_LOG_LEVEL
        value: "INFO"
      - key: NAKAMA_SERVER_KEY
        sync: false
      - key: NAKAMA_CONSOLE_USERNAME
        sync: false
      - key: NAKAMA_CONSOLE_PASSWORD
        sync: false

databases:
  - name: nakama-db
    databaseName: nakama
    ipAllowList: []
